### ISSUE TITLE
During deployment make sure the "current" symlink does not get deleted

### ISSUE THREAD

**Issue by jacobsenj** [TYPO3/Surf#29]
Occassionaly it is possible that while a depoyment is running and the current symlink got deleted, that the webserver would create the directories in order to write to typo3temp. Thus a current/.../typo3temp structure would have been created, preventing surf to create the current symlink pointing to the new release.

**Comment by helhum** [comment]
> the webserver would create the directories

It would be good, if you could outline steps to reproduce (what happens exactl by what code in what order)

But my assumtion is, that the only way to prevent this is to switch current symlink to a maintenance page automatically, once the deployment has started. 

Optional tasks for that could be useful.

Would such a feature be a solution for your scenario?

**Comment by jacobsenj** [comment]
Actually trying to reproduce it, is very hard. It happens occasionally when we deploy one of our bigger TYPO3 installations. Right before the timeframe where the link gets removed a call to the website must have been performed. So a php/TYPO3 call was running while the link was removed and the cache folder was created with its full path in /var/www/hosting/releases/current/src/typo3temp/Cache/... making it impossible for surf to create the current symlink.

We fixed that for now by disallowing the webserver to create stuff in /var/www/hosting/releases while the ssh user can still do it.

**Comment by helhum** [comment]
> So a php/TYPO3 call was running while the link was removed and the cache folder was created with its full path in /var/www/hosting/releases/current/src/typo3temp/Cache/... making it impossible for surf to create the current symlink.

So you are saying the following happens in this exact order:

1. A request comes in, hitting the index.php "behind" the "current" symlink
1. Surf deletes the symlink
1. TYPO3 hits the point in the bootstrap where cache folder should be created
1. TYPO3 creates the **complete** cache directory recursively (including the "current" directory)

This means it would be reproducible when

1. PATH_site is a symlink
1. the symlink is removed once PATH_site is determined (by manually adding this code to the bootstrap)

I will check this.
Imho TYPO3 must never create its root folder, thus this must be fixed in TYPO3
