### ISSUE TITLE
Which kind of applications do you want to deploy? Add yours!

### ISSUE THREAD

**Issue by simonschaufi** [TYPO3/Surf#346]
- Symfony application
- WordPress

It would be great to upgrade these apps remotely (fetch Release zip/tar and deploy):
- owncloud/nextcloud
- Matomo

**Comment by t3easy** [comment]
I would add Static HTML in first place, maybe with a task to add a cache burst to css/js.

**Comment by simonschaufi** [comment]
@t3easy Static HTML files are already possible with the `BaseApplication`. Tasks for Jekyll or anything else can of course be provided.

**Comment by YetiCGN** [comment]
Nope, [Deployer](https://deployer.org/) is already well suited for these kinds of tasks. Really the only reason I use Surf for TYPO3 projects is because it's from the same developers and my guess is they know the system better than somebody who is developing a deployment tool for all kinds of PHP applications.

**Comment by jonaseberle** [comment]
I am going to deploy https://redaxo.org/ with Surf, a system that is basically worse than Wordpress for deployment ;) (fetch release .zip, overlay with local changes, symlink configs, deploy).

Since Surf is received well with colleagues and it is just as easy to add custom tasks as with Deployer, I'd say "why not"?

**Comment by sabbelasichon** [comment]
@simonschaufi I am going to close this issue. Feel free to reopen.

**Comment by sabbelasichon** [comment]
IMHO: Let´s drop this issue. Feel free to open an issue with specific needs in mind. This is too generic for staying alive forever.
