### ISSUE TITLE
[FEATURE] Add notification about deployment status for Slack and others

### ISSUE THREAD

**Issue by simonschaufi** [TYPO3/Surf#347]
I want to be notified about successful or failed deployments via Slack or other communication channels.

**Comment by YetiCGN** [comment]
Our CI tool does that for us. The CI tool calls `vendor/bin/surf -v deploy <target>` as the last step of many after linting, running tests, etc. In my opinion this should not be done in Surf but on the level above it - separation of concern.

**Comment by kaystrobach** [comment]
Imho the wrong scope and you can do it with a shell task already

**Comment by simonschaufi** [comment]
How do you detect if the deployment was successful or had an error?

**Comment by t3easy** [comment]
Surf returns not 0 if the deployment fails so you could check for the return code of the last command with `$?`.
If you need some kind of notification, you run surf in a CI environment, otherwise you would see the error instantly.
If you run it in CI you should use the CI integrations or a shell task. If we include a slack notification, next will be email, Microsoft Teams, WhatsApp, what ever.

**Comment by tgaertner** [comment]
I always create a separate stage for notifications in GitLab-CI. With that its very easy and transparent to set requirements for the job and even do different notifications on success and fail.
I agree that its not a task for surf.
