### ISSUE TITLE
executables are needed to run .phpsh scripts

### ISSUE THREAD

**Issue by sysdef** [TYPO3/Surf#41]
The deployment should start php scripts (like cli_dispatch.phpsh) by using the interpreter, not as executable.

/usr/bin/env php ${site} extbase varnishinstance:update ${iplist}

Reason: Some secured systems are using mount options "nodev,noexec,ro" for the typo3src folder.

**Comment by helhum** [comment]
As you can see here: https://github.com/TYPO3/Surf/blob/master/src/Task/TYPO3/CMS/AbstractCliTask.php#L46-L62
that is already the case for tasks shipped with Surf. This must be the case otherwise deployment would also fail in environments where the correct PHP binary is not available within `/usr/bin/env php`

If you add your own tasks, you need to do so then as well of course. `extbase varnishinstance:update` seems some custom task, which I cannot do much about.

Or do you have a shipped task in mind, which does not prepend the PHP binary?

Anything else I'm missing here?

**Comment by helhum** [comment]
@sysdef Any feedback?
