### ISSUE TITLE
Create Package States Task throws invalid exception

### ISSUE THREAD

**Issue by simonschaufi** [TYPO3/Surf#50]
These lines of code don't make sence:
https://github.com/TYPO3/Surf/blob/master/src/Task/TYPO3/CMS/CreatePackageStatesTask.php#L33-L41

I have not installed typo3_console in typo3conf/ext/ but I indeed have typo3cms in my root folder which is symlinked to vendor/helhum/typo3-console/Scripts/typo3cms.

The exception should only be thrown if BOTH things are false!

**Comment by Sebobo** [comment]
I think the right way would be to check for the `typo3_console` package based on the `vendor-dir` of composer instead of always looking in `typo3conf/ext`.
Then the mentioned code should work fine again.

@simonschaufi you can also set your `vendor-dir` in the composer.json to `typo3conf/ext` for example. Then TYPO3 should also be able to find extensions installed via composer.

**Comment by simonschaufi** [comment]
I wonder why even creating a symlink from typo3conf/ext/typo3_console to vendor dir doesn't work. I thought this could be a workaround...

**Comment by simonschaufi** [comment]
Setting vendor-dir doesn't fix the problem. then the content of vendor is unter typo3conf/ext/ but the extension itself is not directly under vendor.

**Comment by simonschaufi** [comment]
@Sebobo do you have a working surf environment? Could you tell me how you set it up?

**Comment by helhum** [comment]
This is now solved with latest release of TYPO3 Console
